### PR TITLE
Fix typo in code and little simplification - fixes #1

### LINKED ISSUE #1: Project Programmer fails to compile
**Description**
Building the Programmer project with error:
```
Programmer\TargetTester.cpp(448,16): error C2039: 'status': is not a member of 'ETarget'
Programmer\Programmer.hpp(21,7): message : see declaration of 'ETarget'
```
**Repro steps**
1) Build solution

**Environment**
Visual Studio 2022
C++ ver: /std:c++latest
Tested commit: 211c74d1f14c6585e94b28bed1e976f73730ffb9

### PR DESCRIPTION
**Pull request by aborisovich**
Project Programmer failed to build due to typo in the ETarget member name.
Fixed the typo.

Signed-off-by: Andrey Borisovich <business@borisovich.com>

### CODE REVIEW

File: TargetTester.cpp [hunk 1]
```diff
@@ -445,12 +445,10 @@ void TargetProtoTester::run_test(std::function<void(void)> fun,
 		fun();
 	}
 	catch (ETarget& err) {
-		status = err.status;
```
Comment (KokoSoft) [inline TargetTester.cpp]: Names of a class private fields are prefixed with underscore. I was inspired by [google c++ coding style](https://google.github.io/styleguide/cppguide.html#Variable_Names). I decided to make this field public, so there should be no underscore.

File: TargetTester.cpp [hunk 2]
```diff
@@ -445,12 +445,10 @@ void TargetProtoTester::run_test(std::function<void(void)> fun,
...
+		if(err._status != expected_result)
```
Comment (KokoSoft) [inline TargetTester.cpp]: This change alters the function's logic. In the case of negative tests, we will not detect that a `fun` function incorrectly succeeded.

**Review by KokoSoft — COMMENTED** [review]
Thank you for your contribution to the project! I am very pleased that someone was interested in it. I definitely need to choose the coding styles that suit me before the project grows up.

File: TargetTester.cpp (hunk 2 above)
Comment (aborisovich) [reply TargetTester.cpp]: The exception is re-thrown from `catch` block and will propagate until another catch block (catching something of `Exception` type).
So technically the final result is the same.
Meritorically this also has some advantages since you handle an error inside catch block scope (not after it).

Comment (KokoSoft) [reply TargetTester.cpp]: I had in mind a situation where it calls a function that should throw an exception. However, due to an error, it doesn't do it and silently accepts the wrong parameters. In this situation, the error code check will not be performed and we will not detect that we expected an exception.

Comment (aborisovich) [reply TargetTester.cpp]: I think I don't understand what you mean specifically, but ok I'll just revert that change. The main goal of this PR is just to have a project compiled successfully.

Comment (KokoSoft) [reply TargetTester.cpp]: Something like this:
```run_test([] { }, Protocol::STATUS_PROTECTED_ADDR);```
It should throw 'Invalid result' exception.

**Review by KokoSoft — APPROVED** [review]

File: TargetTester.cpp (hunk 2 above)
Comment (aborisovich) [reply TargetTester.cpp]: > Something like this: `run_test([] { }, Protocol::STATUS_PROTECTED_ADDR);` It should throw 'Invalid result' exception.

And it would.
